apiVersion: apps/v1
kind: Deployment
metadata:
  name: argon-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argon-web
  template:
    metadata:
      labels:
        app: argon-web
    spec:
      containers:
      - name: argon-web
        image: balaakashreddyy/argon-web:5   # âœ… Use your actual tag (you pushed tag 5)
        ports:
        - containerPort: 3000
